name: React App Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploying React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          local-dir: build/
          server-dir: ./home/tabletop/public_html/

      - name: Clear Caches
        run: |
          # Add additional cache-clearing commands if necessary

